version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 712aba7e144941ec3a96020a7fd7c896cff587f13f65de535142dbcfa1336b04
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
             # upload test report to Code Climate using `after-build`.
            ./cc-test-reporter after-build
      - store_artifacts:
          path: coverage
          destination: coverage